// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户档案信息
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender        string                 `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	Language      string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	Timezone      string                 `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`
	IsOnline      bool                   `protobuf:"varint,13,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserProfile) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UserProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserProfile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserProfile) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserProfile) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *UserProfile) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 好友关系
type Friendship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint32                 `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // pending, accepted, blocked
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FriendProfile *UserProfile           `protobuf:"bytes,7,opt,name=friend_profile,json=friendProfile,proto3" json:"friend_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friendship) Reset() {
	*x = Friendship{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friendship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friendship) ProtoMessage() {}

func (x *Friendship) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friendship.ProtoReflect.Descriptor instead.
func (*Friendship) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *Friendship) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friendship) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Friendship) GetFriendId() uint32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *Friendship) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Friendship) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Friendship) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Friendship) GetFriendProfile() *UserProfile {
	if x != nil {
		return x.FriendProfile
	}
	return nil
}

// 用户设置
type UserSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PrivacyLevel     string                 `protobuf:"bytes,3,opt,name=privacy_level,json=privacyLevel,proto3" json:"privacy_level,omitempty"`
	AllowSearch      bool                   `protobuf:"varint,4,opt,name=allow_search,json=allowSearch,proto3" json:"allow_search,omitempty"`
	AllowFriendReq   bool                   `protobuf:"varint,5,opt,name=allow_friend_req,json=allowFriendReq,proto3" json:"allow_friend_req,omitempty"`
	ShowOnlineStatus bool                   `protobuf:"varint,6,opt,name=show_online_status,json=showOnlineStatus,proto3" json:"show_online_status,omitempty"`
	ShowLastSeen     bool                   `protobuf:"varint,7,opt,name=show_last_seen,json=showLastSeen,proto3" json:"show_last_seen,omitempty"`
	MessagePreview   bool                   `protobuf:"varint,8,opt,name=message_preview,json=messagePreview,proto3" json:"message_preview,omitempty"`
	SoundEnabled     bool                   `protobuf:"varint,9,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	VibrateEnabled   bool                   `protobuf:"varint,10,opt,name=vibrate_enabled,json=vibrateEnabled,proto3" json:"vibrate_enabled,omitempty"`
	PushEnabled      bool                   `protobuf:"varint,11,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserSettings) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSettings) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSettings) GetPrivacyLevel() string {
	if x != nil {
		return x.PrivacyLevel
	}
	return ""
}

func (x *UserSettings) GetAllowSearch() bool {
	if x != nil {
		return x.AllowSearch
	}
	return false
}

func (x *UserSettings) GetAllowFriendReq() bool {
	if x != nil {
		return x.AllowFriendReq
	}
	return false
}

func (x *UserSettings) GetShowOnlineStatus() bool {
	if x != nil {
		return x.ShowOnlineStatus
	}
	return false
}

func (x *UserSettings) GetShowLastSeen() bool {
	if x != nil {
		return x.ShowLastSeen
	}
	return false
}

func (x *UserSettings) GetMessagePreview() bool {
	if x != nil {
		return x.MessagePreview
	}
	return false
}

func (x *UserSettings) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UserSettings) GetVibrateEnabled() bool {
	if x != nil {
		return x.VibrateEnabled
	}
	return false
}

func (x *UserSettings) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *UserSettings) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserSettings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取用户档案请求
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户档案响应
type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 更新用户档案请求
type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender        string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Language      string                 `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	Timezone      string                 `protobuf:"bytes,11,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserProfileRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdateUserProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// 更新用户档案响应
type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 搜索用户请求
type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                        // 搜索关键词
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 搜索用户响应
type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProfile         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *SearchUsersResponse) GetUsers() []*UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUsersResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 发送好友请求
type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint32                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 可选的请求消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *SendFriendRequestRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetFriendId() uint32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送好友请求响应
type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *SendFriendRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 处理好友请求
type HandleFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendshipId  uint32                 `protobuf:"varint,2,opt,name=friendship_id,json=friendshipId,proto3" json:"friendship_id,omitempty"`
	Accept        bool                   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"` // true=接受, false=拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestRequest) Reset() {
	*x = HandleFriendRequestRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestRequest) ProtoMessage() {}

func (x *HandleFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *HandleFriendRequestRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetFriendshipId() uint32 {
	if x != nil {
		return x.FriendshipId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// 处理好友请求响应
type HandleFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestResponse) Reset() {
	*x = HandleFriendRequestResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestResponse) ProtoMessage() {}

func (x *HandleFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *HandleFriendRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取好友列表请求
type GetFriendsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // pending, accepted, blocked
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsListRequest) Reset() {
	*x = GetFriendsListRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsListRequest) ProtoMessage() {}

func (x *GetFriendsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetFriendsListRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFriendsListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetFriendsListRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFriendsListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取好友列表响应
type GetFriendsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendships   []*Friendship          `protobuf:"bytes,1,rep,name=friendships,proto3" json:"friendships,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsListResponse) Reset() {
	*x = GetFriendsListResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsListResponse) ProtoMessage() {}

func (x *GetFriendsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendsListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetFriendsListResponse) GetFriendships() []*Friendship {
	if x != nil {
		return x.Friendships
	}
	return nil
}

func (x *GetFriendsListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFriendsListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFriendsListResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除好友请求
type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint32                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveFriendRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFriendRequest) GetFriendId() uint32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 删除好友响应
type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveFriendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFriendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 屏蔽用户请求
type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedId     uint32                 `protobuf:"varint,2,opt,name=blocked_id,json=blockedId,proto3" json:"blocked_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *BlockUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BlockUserRequest) GetBlockedId() uint32 {
	if x != nil {
		return x.BlockedId
	}
	return 0
}

func (x *BlockUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 屏蔽用户响应
type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *BlockUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取用户设置请求
type GetUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsRequest) Reset() {
	*x = GetUserSettingsRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsRequest) ProtoMessage() {}

func (x *GetUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserSettingsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户设置响应
type GetUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsResponse) Reset() {
	*x = GetUserSettingsResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsResponse) ProtoMessage() {}

func (x *GetUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserSettingsResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// 更新用户设置请求
type UpdateUserSettingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PrivacyLevel     string                 `protobuf:"bytes,2,opt,name=privacy_level,json=privacyLevel,proto3" json:"privacy_level,omitempty"`
	AllowSearch      bool                   `protobuf:"varint,3,opt,name=allow_search,json=allowSearch,proto3" json:"allow_search,omitempty"`
	AllowFriendReq   bool                   `protobuf:"varint,4,opt,name=allow_friend_req,json=allowFriendReq,proto3" json:"allow_friend_req,omitempty"`
	ShowOnlineStatus bool                   `protobuf:"varint,5,opt,name=show_online_status,json=showOnlineStatus,proto3" json:"show_online_status,omitempty"`
	ShowLastSeen     bool                   `protobuf:"varint,6,opt,name=show_last_seen,json=showLastSeen,proto3" json:"show_last_seen,omitempty"`
	MessagePreview   bool                   `protobuf:"varint,7,opt,name=message_preview,json=messagePreview,proto3" json:"message_preview,omitempty"`
	SoundEnabled     bool                   `protobuf:"varint,8,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	VibrateEnabled   bool                   `protobuf:"varint,9,opt,name=vibrate_enabled,json=vibrateEnabled,proto3" json:"vibrate_enabled,omitempty"`
	PushEnabled      bool                   `protobuf:"varint,10,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserSettingsRequest) Reset() {
	*x = UpdateUserSettingsRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingsRequest) ProtoMessage() {}

func (x *UpdateUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateUserSettingsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserSettingsRequest) GetPrivacyLevel() string {
	if x != nil {
		return x.PrivacyLevel
	}
	return ""
}

func (x *UpdateUserSettingsRequest) GetAllowSearch() bool {
	if x != nil {
		return x.AllowSearch
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetAllowFriendReq() bool {
	if x != nil {
		return x.AllowFriendReq
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetShowOnlineStatus() bool {
	if x != nil {
		return x.ShowOnlineStatus
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetShowLastSeen() bool {
	if x != nil {
		return x.ShowLastSeen
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetMessagePreview() bool {
	if x != nil {
		return x.MessagePreview
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetVibrateEnabled() bool {
	if x != nil {
		return x.VibrateEnabled
	}
	return false
}

func (x *UpdateUserSettingsRequest) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

// 更新用户设置响应
type UpdateUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSettingsResponse) Reset() {
	*x = UpdateUserSettingsResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingsResponse) ProtoMessage() {}

func (x *UpdateUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUserSettingsResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// 更新在线状态请求
type UpdateOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsOnline      bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOnlineStatusRequest) Reset() {
	*x = UpdateOnlineStatusRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOnlineStatusRequest) ProtoMessage() {}

func (x *UpdateOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateOnlineStatusRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateOnlineStatusRequest) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

// 更新在线状态响应
type UpdateOnlineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOnlineStatusResponse) Reset() {
	*x = UpdateOnlineStatusResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOnlineStatusResponse) ProtoMessage() {}

func (x *UpdateOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateOnlineStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x04\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x126\n" +
	"\bbirthday\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\tR\x06gender\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18\f \x01(\tR\btimezone\x12\x1b\n" +
	"\tis_online\x18\r \x01(\bR\bisOnline\x12<\n" +
	"\flast_seen_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x02\n" +
	"\n" +
	"Friendship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x03 \x01(\rR\bfriendId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\x0efriend_profile\x18\a \x01(\v2\x11.user.UserProfileR\rfriendProfile\"\x8d\x04\n" +
	"\fUserSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12#\n" +
	"\rprivacy_level\x18\x03 \x01(\tR\fprivacyLevel\x12!\n" +
	"\fallow_search\x18\x04 \x01(\bR\vallowSearch\x12(\n" +
	"\x10allow_friend_req\x18\x05 \x01(\bR\x0eallowFriendReq\x12,\n" +
	"\x12show_online_status\x18\x06 \x01(\bR\x10showOnlineStatus\x12$\n" +
	"\x0eshow_last_seen\x18\a \x01(\bR\fshowLastSeen\x12'\n" +
	"\x0fmessage_preview\x18\b \x01(\bR\x0emessagePreview\x12#\n" +
	"\rsound_enabled\x18\t \x01(\bR\fsoundEnabled\x12'\n" +
	"\x0fvibrate_enabled\x18\n" +
	" \x01(\bR\x0evibrateEnabled\x12!\n" +
	"\fpush_enabled\x18\v \x01(\bR\vpushEnabled\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"0\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"E\n" +
	"\x16GetUserProfileResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.user.UserProfileR\aprofile\"\xd5\x02\n" +
	"\x18UpdateUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x126\n" +
	"\bbirthday\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x1a\n" +
	"\blanguage\x18\n" +
	" \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18\v \x01(\tR\btimezone\"H\n" +
	"\x19UpdateUserProfileResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.user.UserProfileR\aprofile\"[\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x85\x01\n" +
	"\x13SearchUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.user.UserProfileR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"j\n" +
	"\x18SendFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\rR\bfriendId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\x19SendFriendRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\x1aHandleFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12#\n" +
	"\rfriendship_id\x18\x02 \x01(\rR\ffriendshipId\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\"Q\n" +
	"\x1bHandleFriendRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x15GetFriendsListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\x93\x01\n" +
	"\x16GetFriendsListResponse\x122\n" +
	"\vfriendships\x18\x01 \x03(\v2\x10.user.FriendshipR\vfriendships\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"K\n" +
	"\x13RemoveFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\rR\bfriendId\"J\n" +
	"\x14RemoveFriendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x10BlockUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"blocked_id\x18\x02 \x01(\rR\tblockedId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"G\n" +
	"\x11BlockUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x16GetUserSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"I\n" +
	"\x17GetUserSettingsResponse\x12.\n" +
	"\bsettings\x18\x01 \x01(\v2\x12.user.UserSettingsR\bsettings\"\x94\x03\n" +
	"\x19UpdateUserSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12#\n" +
	"\rprivacy_level\x18\x02 \x01(\tR\fprivacyLevel\x12!\n" +
	"\fallow_search\x18\x03 \x01(\bR\vallowSearch\x12(\n" +
	"\x10allow_friend_req\x18\x04 \x01(\bR\x0eallowFriendReq\x12,\n" +
	"\x12show_online_status\x18\x05 \x01(\bR\x10showOnlineStatus\x12$\n" +
	"\x0eshow_last_seen\x18\x06 \x01(\bR\fshowLastSeen\x12'\n" +
	"\x0fmessage_preview\x18\a \x01(\bR\x0emessagePreview\x12#\n" +
	"\rsound_enabled\x18\b \x01(\bR\fsoundEnabled\x12'\n" +
	"\x0fvibrate_enabled\x18\t \x01(\bR\x0evibrateEnabled\x12!\n" +
	"\fpush_enabled\x18\n" +
	" \x01(\bR\vpushEnabled\"L\n" +
	"\x1aUpdateUserSettingsResponse\x12.\n" +
	"\bsettings\x18\x01 \x01(\v2\x12.user.UserSettingsR\bsettings\"Q\n" +
	"\x19UpdateOnlineStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\"6\n" +
	"\x1aUpdateOnlineStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfa\x06\n" +
	"\vUserService\x12K\n" +
	"\x0eGetUserProfile\x12\x1b.user.GetUserProfileRequest\x1a\x1c.user.GetUserProfileResponse\x12T\n" +
	"\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x1f.user.UpdateUserProfileResponse\x12B\n" +
	"\vSearchUsers\x12\x18.user.SearchUsersRequest\x1a\x19.user.SearchUsersResponse\x12T\n" +
	"\x11SendFriendRequest\x12\x1e.user.SendFriendRequestRequest\x1a\x1f.user.SendFriendRequestResponse\x12Z\n" +
	"\x13HandleFriendRequest\x12 .user.HandleFriendRequestRequest\x1a!.user.HandleFriendRequestResponse\x12K\n" +
	"\x0eGetFriendsList\x12\x1b.user.GetFriendsListRequest\x1a\x1c.user.GetFriendsListResponse\x12E\n" +
	"\fRemoveFriend\x12\x19.user.RemoveFriendRequest\x1a\x1a.user.RemoveFriendResponse\x12<\n" +
	"\tBlockUser\x12\x16.user.BlockUserRequest\x1a\x17.user.BlockUserResponse\x12N\n" +
	"\x0fGetUserSettings\x12\x1c.user.GetUserSettingsRequest\x1a\x1d.user.GetUserSettingsResponse\x12W\n" +
	"\x12UpdateUserSettings\x12\x1f.user.UpdateUserSettingsRequest\x1a .user.UpdateUserSettingsResponse\x12W\n" +
	"\x12UpdateOnlineStatus\x12\x1f.user.UpdateOnlineStatusRequest\x1a .user.UpdateOnlineStatusResponseB;Z9github.com/jacl-coder/telegramlite/user_service/api/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_user_proto_goTypes = []any{
	(*UserProfile)(nil),                 // 0: user.UserProfile
	(*Friendship)(nil),                  // 1: user.Friendship
	(*UserSettings)(nil),                // 2: user.UserSettings
	(*GetUserProfileRequest)(nil),       // 3: user.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),      // 4: user.GetUserProfileResponse
	(*UpdateUserProfileRequest)(nil),    // 5: user.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil),   // 6: user.UpdateUserProfileResponse
	(*SearchUsersRequest)(nil),          // 7: user.SearchUsersRequest
	(*SearchUsersResponse)(nil),         // 8: user.SearchUsersResponse
	(*SendFriendRequestRequest)(nil),    // 9: user.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),   // 10: user.SendFriendRequestResponse
	(*HandleFriendRequestRequest)(nil),  // 11: user.HandleFriendRequestRequest
	(*HandleFriendRequestResponse)(nil), // 12: user.HandleFriendRequestResponse
	(*GetFriendsListRequest)(nil),       // 13: user.GetFriendsListRequest
	(*GetFriendsListResponse)(nil),      // 14: user.GetFriendsListResponse
	(*RemoveFriendRequest)(nil),         // 15: user.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),        // 16: user.RemoveFriendResponse
	(*BlockUserRequest)(nil),            // 17: user.BlockUserRequest
	(*BlockUserResponse)(nil),           // 18: user.BlockUserResponse
	(*GetUserSettingsRequest)(nil),      // 19: user.GetUserSettingsRequest
	(*GetUserSettingsResponse)(nil),     // 20: user.GetUserSettingsResponse
	(*UpdateUserSettingsRequest)(nil),   // 21: user.UpdateUserSettingsRequest
	(*UpdateUserSettingsResponse)(nil),  // 22: user.UpdateUserSettingsResponse
	(*UpdateOnlineStatusRequest)(nil),   // 23: user.UpdateOnlineStatusRequest
	(*UpdateOnlineStatusResponse)(nil),  // 24: user.UpdateOnlineStatusResponse
	(*timestamppb.Timestamp)(nil),       // 25: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	25, // 0: user.UserProfile.birthday:type_name -> google.protobuf.Timestamp
	25, // 1: user.UserProfile.last_seen_at:type_name -> google.protobuf.Timestamp
	25, // 2: user.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	25, // 3: user.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	25, // 4: user.Friendship.created_at:type_name -> google.protobuf.Timestamp
	25, // 5: user.Friendship.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: user.Friendship.friend_profile:type_name -> user.UserProfile
	25, // 7: user.UserSettings.created_at:type_name -> google.protobuf.Timestamp
	25, // 8: user.UserSettings.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: user.GetUserProfileResponse.profile:type_name -> user.UserProfile
	25, // 10: user.UpdateUserProfileRequest.birthday:type_name -> google.protobuf.Timestamp
	0,  // 11: user.UpdateUserProfileResponse.profile:type_name -> user.UserProfile
	0,  // 12: user.SearchUsersResponse.users:type_name -> user.UserProfile
	1,  // 13: user.GetFriendsListResponse.friendships:type_name -> user.Friendship
	2,  // 14: user.GetUserSettingsResponse.settings:type_name -> user.UserSettings
	2,  // 15: user.UpdateUserSettingsResponse.settings:type_name -> user.UserSettings
	3,  // 16: user.UserService.GetUserProfile:input_type -> user.GetUserProfileRequest
	5,  // 17: user.UserService.UpdateUserProfile:input_type -> user.UpdateUserProfileRequest
	7,  // 18: user.UserService.SearchUsers:input_type -> user.SearchUsersRequest
	9,  // 19: user.UserService.SendFriendRequest:input_type -> user.SendFriendRequestRequest
	11, // 20: user.UserService.HandleFriendRequest:input_type -> user.HandleFriendRequestRequest
	13, // 21: user.UserService.GetFriendsList:input_type -> user.GetFriendsListRequest
	15, // 22: user.UserService.RemoveFriend:input_type -> user.RemoveFriendRequest
	17, // 23: user.UserService.BlockUser:input_type -> user.BlockUserRequest
	19, // 24: user.UserService.GetUserSettings:input_type -> user.GetUserSettingsRequest
	21, // 25: user.UserService.UpdateUserSettings:input_type -> user.UpdateUserSettingsRequest
	23, // 26: user.UserService.UpdateOnlineStatus:input_type -> user.UpdateOnlineStatusRequest
	4,  // 27: user.UserService.GetUserProfile:output_type -> user.GetUserProfileResponse
	6,  // 28: user.UserService.UpdateUserProfile:output_type -> user.UpdateUserProfileResponse
	8,  // 29: user.UserService.SearchUsers:output_type -> user.SearchUsersResponse
	10, // 30: user.UserService.SendFriendRequest:output_type -> user.SendFriendRequestResponse
	12, // 31: user.UserService.HandleFriendRequest:output_type -> user.HandleFriendRequestResponse
	14, // 32: user.UserService.GetFriendsList:output_type -> user.GetFriendsListResponse
	16, // 33: user.UserService.RemoveFriend:output_type -> user.RemoveFriendResponse
	18, // 34: user.UserService.BlockUser:output_type -> user.BlockUserResponse
	20, // 35: user.UserService.GetUserSettings:output_type -> user.GetUserSettingsResponse
	22, // 36: user.UserService.UpdateUserSettings:output_type -> user.UpdateUserSettingsResponse
	24, // 37: user.UserService.UpdateOnlineStatus:output_type -> user.UpdateOnlineStatusResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
