server:
  port: 8080
  grpc_port: 50051
  mode: debug # debug, release

database:
  host: localhost
  port: 5432
  user: postgres
  password: "1024"
  dbname: telegramlite
  sslmode: disable

redis:
  addr: localhost:6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expire_hours: 24
  refresh_expire_hours: 168 # 7 days

log:
  level: debug # debug, info, warn, error
  format: json # json, text
  output: file # stdout, file
  file_path: "./logs/auth-service.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 7 # days
  compress: true
  service_name: "auth-service"
