// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 设备类型枚举
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_IOS         DeviceType = 1
	DeviceType_DEVICE_TYPE_ANDROID     DeviceType = 2
	DeviceType_DEVICE_TYPE_WEB         DeviceType = 3
	DeviceType_DEVICE_TYPE_DESKTOP     DeviceType = 4
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_IOS",
		2: "DEVICE_TYPE_ANDROID",
		3: "DEVICE_TYPE_WEB",
		4: "DEVICE_TYPE_DESKTOP",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_IOS":         1,
		"DEVICE_TYPE_ANDROID":     2,
		"DEVICE_TYPE_WEB":         3,
		"DEVICE_TYPE_DESKTOP":     4,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

// 通用响应结构
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`          // 状态码 0=成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`     // 响应消息
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 响应时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 用户信息 (Auth Service 视角)
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserInfo) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 设备信息
type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceToken   string                 `protobuf:"bytes,3,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,4,opt,name=device_type,json=deviceType,proto3,enum=telegramlite.auth.DeviceType" json:"device_type,omitempty"`
	DeviceName    string                 `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	PushToken     string                 `protobuf:"bytes,6,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	IsOnline      bool                   `protobuf:"varint,7,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeviceInfo) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *DeviceInfo) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *DeviceInfo) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *DeviceInfo) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *DeviceInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Token 信息
type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`  // Bearer
	ExpiresIn     int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *TokenInfo) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenInfo) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenInfo) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenInfo) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DeviceToken   string                 `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,6,opt,name=device_type,json=deviceType,proto3,enum=telegramlite.auth.DeviceType" json:"device_type,omitempty"`
	DeviceName    string                 `protobuf:"bytes,7,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *RegisterRequest) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *RegisterRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          *RegisterData          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterResponse) GetData() *RegisterData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Device        *DeviceInfo            `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Token         *TokenInfo             `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterData) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterData) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *RegisterData) GetToken() *TokenInfo {
	if x != nil {
		return x.Token
	}
	return nil
}

// 登录请求
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*LoginRequest_Phone
	//	*LoginRequest_Email
	//	*LoginRequest_Username
	Credential    isLoginRequest_Credential `protobuf_oneof:"credential"`
	Password      string                    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DeviceToken   string                    `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	DeviceType    DeviceType                `protobuf:"varint,6,opt,name=device_type,json=deviceType,proto3,enum=telegramlite.auth.DeviceType" json:"device_type,omitempty"`
	DeviceName    string                    `protobuf:"bytes,7,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetCredential() isLoginRequest_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Credential.(*LoginRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Credential.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Credential.(*LoginRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *LoginRequest) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *LoginRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type isLoginRequest_Credential interface {
	isLoginRequest_Credential()
}

type LoginRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,3,opt,name=username,proto3,oneof"`
}

func (*LoginRequest_Phone) isLoginRequest_Credential() {}

func (*LoginRequest_Email) isLoginRequest_Credential() {}

func (*LoginRequest_Username) isLoginRequest_Credential() {}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          *LoginData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LoginResponse) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Device        *DeviceInfo            `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Token         *TokenInfo             `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LoginData) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginData) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *LoginData) GetToken() *TokenInfo {
	if x != nil {
		return x.Token
	}
	return nil
}

// 刷新Token请求
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 刷新Token响应
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Token         *TokenInfo             `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RefreshTokenResponse) GetToken() *TokenInfo {
	if x != nil {
		return x.Token
	}
	return nil
}

// 注销请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *LogoutRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

// 注销响应
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LogoutResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// 验证Token请求 (内部服务调用)
type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 验证Token响应
type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          *VerifyTokenData       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyTokenResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *VerifyTokenResponse) GetData() *VerifyTokenData {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerifyTokenData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceToken   string                 `protobuf:"bytes,4,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenData) Reset() {
	*x = VerifyTokenData{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenData) ProtoMessage() {}

func (x *VerifyTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenData.ProtoReflect.Descriptor instead.
func (*VerifyTokenData) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyTokenData) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenData) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenData) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *VerifyTokenData) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *VerifyTokenData) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 获取用户信息响应
type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserInfoResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetUserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{19}
}

// 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          *HealthData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *HealthResponse) GetData() *HealthData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthData) Reset() {
	*x = HealthData{}
	mi := &file_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthData) ProtoMessage() {}

func (x *HealthData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthData.ProtoReflect.Descriptor instead.
func (*HealthData) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{21}
}

func (x *HealthData) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x11telegramlite.auth\x1a\x1fgoogle/protobuf/timestamp.proto\"r\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd4\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12>\n" +
	"\rlast_login_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xee\x02\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fdevice_token\x18\x03 \x01(\tR\vdeviceToken\x12>\n" +
	"\vdevice_type\x18\x04 \x01(\x0e2\x1d.telegramlite.auth.DeviceTypeR\n" +
	"deviceType\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12\x1d\n" +
	"\n" +
	"push_token\x18\x06 \x01(\tR\tpushToken\x12\x1b\n" +
	"\tis_online\x18\a \x01(\bR\bisOnline\x12<\n" +
	"\flast_seen_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x01\n" +
	"\tTokenInfo\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\"\xf9\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fdevice_token\x18\x05 \x01(\tR\vdeviceToken\x12>\n" +
	"\vdevice_type\x18\x06 \x01(\x0e2\x1d.telegramlite.auth.DeviceTypeR\n" +
	"deviceType\x12\x1f\n" +
	"\vdevice_name\x18\a \x01(\tR\n" +
	"deviceName\"\x80\x01\n" +
	"\x10RegisterResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.telegramlite.auth.RegisterDataR\x04data\"\xaa\x01\n" +
	"\fRegisterData\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.telegramlite.auth.UserInfoR\x04user\x125\n" +
	"\x06device\x18\x02 \x01(\v2\x1d.telegramlite.auth.DeviceInfoR\x06device\x122\n" +
	"\x05token\x18\x03 \x01(\v2\x1c.telegramlite.auth.TokenInfoR\x05token\"\x8a\x02\n" +
	"\fLoginRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fdevice_token\x18\x05 \x01(\tR\vdeviceToken\x12>\n" +
	"\vdevice_type\x18\x06 \x01(\x0e2\x1d.telegramlite.auth.DeviceTypeR\n" +
	"deviceType\x12\x1f\n" +
	"\vdevice_name\x18\a \x01(\tR\n" +
	"deviceNameB\f\n" +
	"\n" +
	"credential\"z\n" +
	"\rLoginResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1c.telegramlite.auth.LoginDataR\x04data\"\xa7\x01\n" +
	"\tLoginData\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.telegramlite.auth.UserInfoR\x04user\x125\n" +
	"\x06device\x18\x02 \x01(\v2\x1d.telegramlite.auth.DeviceInfoR\x06device\x122\n" +
	"\x05token\x18\x03 \x01(\v2\x1c.telegramlite.auth.TokenInfoR\x05token\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x83\x01\n" +
	"\x14RefreshTokenResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\x122\n" +
	"\x05token\x18\x02 \x01(\v2\x1c.telegramlite.auth.TokenInfoR\x05token\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\"I\n" +
	"\x0eLogoutResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\"7\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x86\x01\n" +
	"\x13VerifyTokenResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\x126\n" +
	"\x04data\x18\x02 \x01(\v2\".telegramlite.auth.VerifyTokenDataR\x04data\"\xbb\x01\n" +
	"\x0fVerifyTokenData\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\x04R\bdeviceId\x12!\n" +
	"\fdevice_token\x18\x04 \x01(\tR\vdeviceToken\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"7\n" +
	"\x12GetUserInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x7f\n" +
	"\x13GetUserInfoResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\x12/\n" +
	"\x04user\x18\x02 \x01(\v2\x1b.telegramlite.auth.UserInfoR\x04user\"\x0f\n" +
	"\rHealthRequest\"|\n" +
	"\x0eHealthResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.telegramlite.auth.ResponseR\bresponse\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.telegramlite.auth.HealthDataR\x04data\"x\n" +
	"\n" +
	"HealthData\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\x85\x01\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDEVICE_TYPE_IOS\x10\x01\x12\x17\n" +
	"\x13DEVICE_TYPE_ANDROID\x10\x02\x12\x13\n" +
	"\x0fDEVICE_TYPE_WEB\x10\x03\x12\x17\n" +
	"\x13DEVICE_TYPE_DESKTOP\x10\x042\xe9\x04\n" +
	"\vAuthService\x12S\n" +
	"\bRegister\x12\".telegramlite.auth.RegisterRequest\x1a#.telegramlite.auth.RegisterResponse\x12J\n" +
	"\x05Login\x12\x1f.telegramlite.auth.LoginRequest\x1a .telegramlite.auth.LoginResponse\x12_\n" +
	"\fRefreshToken\x12&.telegramlite.auth.RefreshTokenRequest\x1a'.telegramlite.auth.RefreshTokenResponse\x12M\n" +
	"\x06Logout\x12 .telegramlite.auth.LogoutRequest\x1a!.telegramlite.auth.LogoutResponse\x12\\\n" +
	"\vVerifyToken\x12%.telegramlite.auth.VerifyTokenRequest\x1a&.telegramlite.auth.VerifyTokenResponse\x12\\\n" +
	"\vGetUserInfo\x12%.telegramlite.auth.GetUserInfoRequest\x1a&.telegramlite.auth.GetUserInfoResponse\x12M\n" +
	"\x06Health\x12 .telegramlite.auth.HealthRequest\x1a!.telegramlite.auth.HealthResponseB;Z9github.com/jacl-coder/telegramlite/auth_service/api/protob\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_auth_proto_goTypes = []any{
	(DeviceType)(0),               // 0: telegramlite.auth.DeviceType
	(*Response)(nil),              // 1: telegramlite.auth.Response
	(*UserInfo)(nil),              // 2: telegramlite.auth.UserInfo
	(*DeviceInfo)(nil),            // 3: telegramlite.auth.DeviceInfo
	(*TokenInfo)(nil),             // 4: telegramlite.auth.TokenInfo
	(*RegisterRequest)(nil),       // 5: telegramlite.auth.RegisterRequest
	(*RegisterResponse)(nil),      // 6: telegramlite.auth.RegisterResponse
	(*RegisterData)(nil),          // 7: telegramlite.auth.RegisterData
	(*LoginRequest)(nil),          // 8: telegramlite.auth.LoginRequest
	(*LoginResponse)(nil),         // 9: telegramlite.auth.LoginResponse
	(*LoginData)(nil),             // 10: telegramlite.auth.LoginData
	(*RefreshTokenRequest)(nil),   // 11: telegramlite.auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),  // 12: telegramlite.auth.RefreshTokenResponse
	(*LogoutRequest)(nil),         // 13: telegramlite.auth.LogoutRequest
	(*LogoutResponse)(nil),        // 14: telegramlite.auth.LogoutResponse
	(*VerifyTokenRequest)(nil),    // 15: telegramlite.auth.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),   // 16: telegramlite.auth.VerifyTokenResponse
	(*VerifyTokenData)(nil),       // 17: telegramlite.auth.VerifyTokenData
	(*GetUserInfoRequest)(nil),    // 18: telegramlite.auth.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),   // 19: telegramlite.auth.GetUserInfoResponse
	(*HealthRequest)(nil),         // 20: telegramlite.auth.HealthRequest
	(*HealthResponse)(nil),        // 21: telegramlite.auth.HealthResponse
	(*HealthData)(nil),            // 22: telegramlite.auth.HealthData
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_auth_proto_depIdxs = []int32{
	23, // 0: telegramlite.auth.Response.timestamp:type_name -> google.protobuf.Timestamp
	23, // 1: telegramlite.auth.UserInfo.last_login_at:type_name -> google.protobuf.Timestamp
	23, // 2: telegramlite.auth.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 3: telegramlite.auth.UserInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: telegramlite.auth.DeviceInfo.device_type:type_name -> telegramlite.auth.DeviceType
	23, // 5: telegramlite.auth.DeviceInfo.last_seen_at:type_name -> google.protobuf.Timestamp
	23, // 6: telegramlite.auth.DeviceInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: telegramlite.auth.RegisterRequest.device_type:type_name -> telegramlite.auth.DeviceType
	1,  // 8: telegramlite.auth.RegisterResponse.response:type_name -> telegramlite.auth.Response
	7,  // 9: telegramlite.auth.RegisterResponse.data:type_name -> telegramlite.auth.RegisterData
	2,  // 10: telegramlite.auth.RegisterData.user:type_name -> telegramlite.auth.UserInfo
	3,  // 11: telegramlite.auth.RegisterData.device:type_name -> telegramlite.auth.DeviceInfo
	4,  // 12: telegramlite.auth.RegisterData.token:type_name -> telegramlite.auth.TokenInfo
	0,  // 13: telegramlite.auth.LoginRequest.device_type:type_name -> telegramlite.auth.DeviceType
	1,  // 14: telegramlite.auth.LoginResponse.response:type_name -> telegramlite.auth.Response
	10, // 15: telegramlite.auth.LoginResponse.data:type_name -> telegramlite.auth.LoginData
	2,  // 16: telegramlite.auth.LoginData.user:type_name -> telegramlite.auth.UserInfo
	3,  // 17: telegramlite.auth.LoginData.device:type_name -> telegramlite.auth.DeviceInfo
	4,  // 18: telegramlite.auth.LoginData.token:type_name -> telegramlite.auth.TokenInfo
	1,  // 19: telegramlite.auth.RefreshTokenResponse.response:type_name -> telegramlite.auth.Response
	4,  // 20: telegramlite.auth.RefreshTokenResponse.token:type_name -> telegramlite.auth.TokenInfo
	1,  // 21: telegramlite.auth.LogoutResponse.response:type_name -> telegramlite.auth.Response
	1,  // 22: telegramlite.auth.VerifyTokenResponse.response:type_name -> telegramlite.auth.Response
	17, // 23: telegramlite.auth.VerifyTokenResponse.data:type_name -> telegramlite.auth.VerifyTokenData
	23, // 24: telegramlite.auth.VerifyTokenData.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 25: telegramlite.auth.GetUserInfoResponse.response:type_name -> telegramlite.auth.Response
	2,  // 26: telegramlite.auth.GetUserInfoResponse.user:type_name -> telegramlite.auth.UserInfo
	1,  // 27: telegramlite.auth.HealthResponse.response:type_name -> telegramlite.auth.Response
	22, // 28: telegramlite.auth.HealthResponse.data:type_name -> telegramlite.auth.HealthData
	23, // 29: telegramlite.auth.HealthData.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 30: telegramlite.auth.AuthService.Register:input_type -> telegramlite.auth.RegisterRequest
	8,  // 31: telegramlite.auth.AuthService.Login:input_type -> telegramlite.auth.LoginRequest
	11, // 32: telegramlite.auth.AuthService.RefreshToken:input_type -> telegramlite.auth.RefreshTokenRequest
	13, // 33: telegramlite.auth.AuthService.Logout:input_type -> telegramlite.auth.LogoutRequest
	15, // 34: telegramlite.auth.AuthService.VerifyToken:input_type -> telegramlite.auth.VerifyTokenRequest
	18, // 35: telegramlite.auth.AuthService.GetUserInfo:input_type -> telegramlite.auth.GetUserInfoRequest
	20, // 36: telegramlite.auth.AuthService.Health:input_type -> telegramlite.auth.HealthRequest
	6,  // 37: telegramlite.auth.AuthService.Register:output_type -> telegramlite.auth.RegisterResponse
	9,  // 38: telegramlite.auth.AuthService.Login:output_type -> telegramlite.auth.LoginResponse
	12, // 39: telegramlite.auth.AuthService.RefreshToken:output_type -> telegramlite.auth.RefreshTokenResponse
	14, // 40: telegramlite.auth.AuthService.Logout:output_type -> telegramlite.auth.LogoutResponse
	16, // 41: telegramlite.auth.AuthService.VerifyToken:output_type -> telegramlite.auth.VerifyTokenResponse
	19, // 42: telegramlite.auth.AuthService.GetUserInfo:output_type -> telegramlite.auth.GetUserInfoResponse
	21, // 43: telegramlite.auth.AuthService.Health:output_type -> telegramlite.auth.HealthResponse
	37, // [37:44] is the sub-list for method output_type
	30, // [30:37] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_auth_proto_msgTypes[7].OneofWrappers = []any{
		(*LoginRequest_Phone)(nil),
		(*LoginRequest_Email)(nil),
		(*LoginRequest_Username)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
